#############################################################################
# Makefile for building: fahrplan
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sun May 6 20:46:12 2018
# Project:  fahrplan.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile fahrplan.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GL_NO_SCISSOR_TEST -DQT_DEFAULT_TEXTURE_GLYPH_CACHE_WIDTH=1024 -DQT_NO_DEBUG -DQT_MAEMO5_LIB -DQT_XMLPATTERNS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -fno-omit-frame-pointer -fno-optimize-sibling-calls -DQT_SHARED -I/usr/include/QtCore -I/usr/include/calendar-backend -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -fno-omit-frame-pointer -fno-optimize-sibling-calls -DQT_SHARED -I/usr/include/QtCore -I/usr/include/calendar-backend -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/linux-g++-maemo5 -I. -I/targets/FREMANTLE_ARMEL/usr/include/QtCore -I/targets/FREMANTLE_ARMEL/usr/include/QtNetwork -I/targets/FREMANTLE_ARMEL/usr/include/QtGui -I/targets/FREMANTLE_ARMEL/usr/include/QtXmlPatterns -I/targets/FREMANTLE_ARMEL/usr/include/QtMaemo5 -I/targets/FREMANTLE_ARMEL/usr/include -I/targets/FREMANTLE_ARMEL/usr/include/QtLocation -I/targets/FREMANTLE_ARMEL/usr/include/QtDBus -I. -I/targets/FREMANTLE_ARMEL/usr/include
LINK          = g++
LFLAGS        = -Wl,-rpath-link,/usr/lib -Wl,-O1 -Wl,--hash-style=gnu -Wl,-rpath,/usr/lib -Wl,-rpath,/usr/lib
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/lib/ -lqjson -L/usr/lib -lcalendar_backend -lQtLocation -lQtMaemo5 -L/usr/X11R6/lib -lQtXmlPatterns -lQtGui -lQtNetwork -lQtDBus -lQtXml -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		parser_mobilebahnde.cpp \
		selectstationdialog.cpp \
		parser_abstract.cpp \
		parser_mvvde.cpp \
		configdialog.cpp \
		backupgpsopenstreetmap.cpp \
		fahrplanutils.cpp \
		parser_sbbch.cpp \
		calendardialog.cpp \
		parser_131500comau.cpp \
		qvaluebutton.cpp \
		parser_hafasxml.cpp \
		parser_xmloebbat.cpp \
		parser_xmlsbbch.cpp \
		parser_xmlrejseplanendk.cpp \
		parser_translink.cpp moc_mainwindow.cpp \
		moc_parser_mobilebahnde.cpp \
		moc_selectstationdialog.cpp \
		moc_parser_abstract.cpp \
		moc_parser_mvvde.cpp \
		moc_configdialog.cpp \
		moc_backupgpsopenstreetmap.cpp \
		moc_parser_sbbch.cpp \
		moc_calendardialog.cpp \
		moc_parser_131500comau.cpp \
		moc_qvaluebutton.cpp \
		moc_parser_hafasxml.cpp \
		moc_parser_xmloebbat.cpp \
		moc_parser_xmlsbbch.cpp \
		moc_parser_xmlrejseplanendk.cpp \
		moc_parser_translink.cpp \
		qrc_fahrplan.cpp
OBJECTS       = main.o \
		mainwindow.o \
		parser_mobilebahnde.o \
		selectstationdialog.o \
		parser_abstract.o \
		parser_mvvde.o \
		configdialog.o \
		backupgpsopenstreetmap.o \
		fahrplanutils.o \
		parser_sbbch.o \
		calendardialog.o \
		parser_131500comau.o \
		qvaluebutton.o \
		parser_hafasxml.o \
		parser_xmloebbat.o \
		parser_xmlsbbch.o \
		parser_xmlrejseplanendk.o \
		parser_translink.o \
		moc_mainwindow.o \
		moc_parser_mobilebahnde.o \
		moc_selectstationdialog.o \
		moc_parser_abstract.o \
		moc_parser_mvvde.o \
		moc_configdialog.o \
		moc_backupgpsopenstreetmap.o \
		moc_parser_sbbch.o \
		moc_calendardialog.o \
		moc_parser_131500comau.o \
		moc_qvaluebutton.o \
		moc_parser_hafasxml.o \
		moc_parser_xmloebbat.o \
		moc_parser_xmlsbbch.o \
		moc_parser_xmlrejseplanendk.o \
		moc_parser_translink.o \
		qrc_fahrplan.o
DIST          = /targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/default_pre.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/release.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qdbus.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/mobility.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/lex.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		fahrplan.pro
QMAKE_TARGET  = fahrplan
DESTDIR       = 
TARGET        = fahrplan

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fahrplan.pro  /targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/linux-g++-maemo5/qmake.conf /targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/default_pre.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/release.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qdbus.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/mobility.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/lex.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtMaemo5.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtXmlPatterns.prl \
		/usr/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile fahrplan.pro
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/common/unix.conf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/common/linux.conf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/qconfig.pri:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt_functions.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt_config.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/default_pre.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/release.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/default_post.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qdbus.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/moc.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/mobility.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/warn_on.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/unix/thread.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/resources.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/uic.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/yacc.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/lex.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtCore.prl:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtMaemo5.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtXmlPatterns.prl:
/usr/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile fahrplan.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/fahrplan1.0.0 || $(MKDIR) .tmp/fahrplan1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/fahrplan1.0.0/ && $(COPY_FILE) --parents mainwindow.h parser_mobilebahnde.h selectstationdialog.h parser_abstract.h parser_mvvde.h configdialog.h backupgpsopenstreetmap.h fahrplanutils.h parser_sbbch.h calendardialog.h parser_131500comau.h qvaluebutton.h parser_hafasxml.h parser_xmloebbat.h parser_xmlsbbch.h parser_xmlrejseplanendk.h parser_translink.h .tmp/fahrplan1.0.0/ && $(COPY_FILE) --parents fahrplan.qrc .tmp/fahrplan1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp parser_mobilebahnde.cpp selectstationdialog.cpp parser_abstract.cpp parser_mvvde.cpp configdialog.cpp backupgpsopenstreetmap.cpp fahrplanutils.cpp parser_sbbch.cpp calendardialog.cpp parser_131500comau.cpp qvaluebutton.cpp parser_hafasxml.cpp parser_xmloebbat.cpp parser_xmlsbbch.cpp parser_xmlrejseplanendk.cpp parser_translink.cpp .tmp/fahrplan1.0.0/ && $(COPY_FILE) --parents fahrplan_de.ts fahrplan_fr.ts .tmp/fahrplan1.0.0/ && (cd `dirname .tmp/fahrplan1.0.0` && $(TAR) fahrplan1.0.0.tar fahrplan1.0.0 && $(COMPRESS) fahrplan1.0.0.tar) && $(MOVE) `dirname .tmp/fahrplan1.0.0`/fahrplan1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/fahrplan1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_parser_mobilebahnde.cpp moc_selectstationdialog.cpp moc_parser_abstract.cpp moc_parser_mvvde.cpp moc_configdialog.cpp moc_backupgpsopenstreetmap.cpp moc_parser_sbbch.cpp moc_calendardialog.cpp moc_parser_131500comau.cpp moc_qvaluebutton.cpp moc_parser_hafasxml.cpp moc_parser_xmloebbat.cpp moc_parser_xmlsbbch.cpp moc_parser_xmlrejseplanendk.cpp moc_parser_translink.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_parser_mobilebahnde.cpp moc_selectstationdialog.cpp moc_parser_abstract.cpp moc_parser_mvvde.cpp moc_configdialog.cpp moc_backupgpsopenstreetmap.cpp moc_parser_sbbch.cpp moc_calendardialog.cpp moc_parser_131500comau.cpp moc_qvaluebutton.cpp moc_parser_hafasxml.cpp moc_parser_xmloebbat.cpp moc_parser_xmlsbbch.cpp moc_parser_xmlrejseplanendk.cpp moc_parser_translink.cpp
moc_mainwindow.cpp: calendardialog.h \
		parser_abstract.h \
		fahrplanutils.h \
		parser_mobilebahnde.h \
		parser_mvvde.h \
		parser_sbbch.h \
		parser_131500comau.h \
		parser_hafasxml.h \
		parser_xmloebbat.h \
		parser_xmlrejseplanendk.h \
		parser_xmlsbbch.h \
		parser_translink.h \
		selectstationdialog.h \
		backupgpsopenstreetmap.h \
		qvaluebutton.h \
		configdialog.h \
		mainwindow.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_parser_mobilebahnde.cpp: parser_abstract.h \
		parser_mobilebahnde.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parser_mobilebahnde.h -o moc_parser_mobilebahnde.cpp

moc_selectstationdialog.cpp: backupgpsopenstreetmap.h \
		fahrplanutils.h \
		parser_abstract.h \
		qvaluebutton.h \
		selectstationdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) selectstationdialog.h -o moc_selectstationdialog.cpp

moc_parser_abstract.cpp: parser_abstract.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parser_abstract.h -o moc_parser_abstract.cpp

moc_parser_mvvde.cpp: parser_abstract.h \
		parser_mvvde.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parser_mvvde.h -o moc_parser_mvvde.cpp

moc_configdialog.cpp: mainwindow.h \
		calendardialog.h \
		parser_abstract.h \
		fahrplanutils.h \
		parser_mobilebahnde.h \
		parser_mvvde.h \
		parser_sbbch.h \
		parser_131500comau.h \
		parser_hafasxml.h \
		parser_xmloebbat.h \
		parser_xmlrejseplanendk.h \
		parser_xmlsbbch.h \
		parser_translink.h \
		selectstationdialog.h \
		backupgpsopenstreetmap.h \
		qvaluebutton.h \
		configdialog.h \
		configdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) configdialog.h -o moc_configdialog.cpp

moc_backupgpsopenstreetmap.cpp: backupgpsopenstreetmap.h
	/usr/bin/moc $(DEFINES) $(INCPATH) backupgpsopenstreetmap.h -o moc_backupgpsopenstreetmap.cpp

moc_parser_sbbch.cpp: parser_abstract.h \
		parser_sbbch.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parser_sbbch.h -o moc_parser_sbbch.cpp

moc_calendardialog.cpp: parser_abstract.h \
		fahrplanutils.h \
		calendardialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) calendardialog.h -o moc_calendardialog.cpp

moc_parser_131500comau.cpp: fahrplanutils.h \
		parser_abstract.h \
		parser_131500comau.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parser_131500comau.h -o moc_parser_131500comau.cpp

moc_qvaluebutton.cpp: qvaluebutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qvaluebutton.h -o moc_qvaluebutton.cpp

moc_parser_hafasxml.cpp: parser_abstract.h \
		parser_hafasxml.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parser_hafasxml.h -o moc_parser_hafasxml.cpp

moc_parser_xmloebbat.cpp: parser_hafasxml.h \
		parser_abstract.h \
		parser_xmloebbat.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parser_xmloebbat.h -o moc_parser_xmloebbat.cpp

moc_parser_xmlsbbch.cpp: parser_hafasxml.h \
		parser_abstract.h \
		parser_xmlsbbch.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parser_xmlsbbch.h -o moc_parser_xmlsbbch.cpp

moc_parser_xmlrejseplanendk.cpp: parser_hafasxml.h \
		parser_abstract.h \
		parser_xmlrejseplanendk.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parser_xmlrejseplanendk.h -o moc_parser_xmlrejseplanendk.cpp

moc_parser_translink.cpp: fahrplanutils.h \
		parser_abstract.h \
		parser_translink.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parser_translink.h -o moc_parser_translink.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all: qrc_fahrplan.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_fahrplan.cpp
qrc_fahrplan.cpp: fahrplan.qrc \
		fahrplan_de.qm \
		fahrplan_fr.qm
	/usr/bin/rcc -name fahrplan fahrplan.qrc -o qrc_fahrplan.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		calendardialog.h \
		parser_abstract.h \
		fahrplanutils.h \
		parser_mobilebahnde.h \
		parser_mvvde.h \
		parser_sbbch.h \
		parser_131500comau.h \
		parser_hafasxml.h \
		parser_xmloebbat.h \
		parser_xmlrejseplanendk.h \
		parser_xmlsbbch.h \
		parser_translink.h \
		selectstationdialog.h \
		backupgpsopenstreetmap.h \
		qvaluebutton.h \
		configdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		calendardialog.h \
		parser_abstract.h \
		fahrplanutils.h \
		parser_mobilebahnde.h \
		parser_mvvde.h \
		parser_sbbch.h \
		parser_131500comau.h \
		parser_hafasxml.h \
		parser_xmloebbat.h \
		parser_xmlrejseplanendk.h \
		parser_xmlsbbch.h \
		parser_translink.h \
		selectstationdialog.h \
		backupgpsopenstreetmap.h \
		qvaluebutton.h \
		configdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

parser_mobilebahnde.o: parser_mobilebahnde.cpp parser_mobilebahnde.h \
		parser_abstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser_mobilebahnde.o parser_mobilebahnde.cpp

selectstationdialog.o: selectstationdialog.cpp selectstationdialog.h \
		backupgpsopenstreetmap.h \
		fahrplanutils.h \
		parser_abstract.h \
		qvaluebutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectstationdialog.o selectstationdialog.cpp

parser_abstract.o: parser_abstract.cpp parser_abstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser_abstract.o parser_abstract.cpp

parser_mvvde.o: parser_mvvde.cpp parser_mvvde.h \
		parser_abstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser_mvvde.o parser_mvvde.cpp

configdialog.o: configdialog.cpp configdialog.h \
		mainwindow.h \
		calendardialog.h \
		parser_abstract.h \
		fahrplanutils.h \
		parser_mobilebahnde.h \
		parser_mvvde.h \
		parser_sbbch.h \
		parser_131500comau.h \
		parser_hafasxml.h \
		parser_xmloebbat.h \
		parser_xmlrejseplanendk.h \
		parser_xmlsbbch.h \
		parser_translink.h \
		selectstationdialog.h \
		backupgpsopenstreetmap.h \
		qvaluebutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialog.o configdialog.cpp

backupgpsopenstreetmap.o: backupgpsopenstreetmap.cpp backupgpsopenstreetmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backupgpsopenstreetmap.o backupgpsopenstreetmap.cpp

fahrplanutils.o: fahrplanutils.cpp fahrplanutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fahrplanutils.o fahrplanutils.cpp

parser_sbbch.o: parser_sbbch.cpp parser_sbbch.h \
		parser_abstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser_sbbch.o parser_sbbch.cpp

calendardialog.o: calendardialog.cpp calendardialog.h \
		parser_abstract.h \
		fahrplanutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calendardialog.o calendardialog.cpp

parser_131500comau.o: parser_131500comau.cpp parser_131500comau.h \
		fahrplanutils.h \
		parser_abstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser_131500comau.o parser_131500comau.cpp

qvaluebutton.o: qvaluebutton.cpp qvaluebutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qvaluebutton.o qvaluebutton.cpp

parser_hafasxml.o: parser_hafasxml.cpp parser_hafasxml.h \
		parser_abstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser_hafasxml.o parser_hafasxml.cpp

parser_xmloebbat.o: parser_xmloebbat.cpp parser_xmloebbat.h \
		parser_hafasxml.h \
		parser_abstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser_xmloebbat.o parser_xmloebbat.cpp

parser_xmlsbbch.o: parser_xmlsbbch.cpp parser_xmlsbbch.h \
		parser_hafasxml.h \
		parser_abstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser_xmlsbbch.o parser_xmlsbbch.cpp

parser_xmlrejseplanendk.o: parser_xmlrejseplanendk.cpp parser_xmlrejseplanendk.h \
		parser_hafasxml.h \
		parser_abstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser_xmlrejseplanendk.o parser_xmlrejseplanendk.cpp

parser_translink.o: parser_translink.cpp parser_translink.h \
		fahrplanutils.h \
		parser_abstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser_translink.o parser_translink.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_parser_mobilebahnde.o: moc_parser_mobilebahnde.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser_mobilebahnde.o moc_parser_mobilebahnde.cpp

moc_selectstationdialog.o: moc_selectstationdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selectstationdialog.o moc_selectstationdialog.cpp

moc_parser_abstract.o: moc_parser_abstract.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser_abstract.o moc_parser_abstract.cpp

moc_parser_mvvde.o: moc_parser_mvvde.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser_mvvde.o moc_parser_mvvde.cpp

moc_configdialog.o: moc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configdialog.o moc_configdialog.cpp

moc_backupgpsopenstreetmap.o: moc_backupgpsopenstreetmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_backupgpsopenstreetmap.o moc_backupgpsopenstreetmap.cpp

moc_parser_sbbch.o: moc_parser_sbbch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser_sbbch.o moc_parser_sbbch.cpp

moc_calendardialog.o: moc_calendardialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calendardialog.o moc_calendardialog.cpp

moc_parser_131500comau.o: moc_parser_131500comau.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser_131500comau.o moc_parser_131500comau.cpp

moc_qvaluebutton.o: moc_qvaluebutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qvaluebutton.o moc_qvaluebutton.cpp

moc_parser_hafasxml.o: moc_parser_hafasxml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser_hafasxml.o moc_parser_hafasxml.cpp

moc_parser_xmloebbat.o: moc_parser_xmloebbat.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser_xmloebbat.o moc_parser_xmloebbat.cpp

moc_parser_xmlsbbch.o: moc_parser_xmlsbbch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser_xmlsbbch.o moc_parser_xmlsbbch.cpp

moc_parser_xmlrejseplanendk.o: moc_parser_xmlrejseplanendk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser_xmlrejseplanendk.o moc_parser_xmlrejseplanendk.cpp

moc_parser_translink.o: moc_parser_translink.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser_translink.o moc_parser_translink.cpp

qrc_fahrplan.o: qrc_fahrplan.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_fahrplan.o qrc_fahrplan.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/fahrplan/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/fahrplan/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/fahrplan/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/fahrplan/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/fahrplan/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/fahrplan/bin/ 


install_desktop: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/hildon/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/hildon/ 
	-$(INSTALL_FILE) /home/maemo/fahrplan-0.0.37/data/fahrplan.desktop $(INSTALL_ROOT)/usr/share/applications/hildon/


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/hildon/fahrplan.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/hildon/ 


install_service: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/dbus-1/services/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/dbus-1/services/ 
	-$(INSTALL_FILE) /home/maemo/fahrplan-0.0.37/data/fahrplan.service $(INSTALL_ROOT)/usr/share/dbus-1/services/


uninstall_service:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dbus-1/services/fahrplan.service
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/dbus-1/services/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/ 
	-$(INSTALL_FILE) /home/maemo/fahrplan-0.0.37/data/fahrplan.png $(INSTALL_ROOT)/usr/share/icons/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/fahrplan.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/ 


install:  install_target install_desktop install_service install_icon  FORCE

uninstall: uninstall_target uninstall_desktop uninstall_service uninstall_icon   FORCE

FORCE:

